package ais.tee.data.tokenizer

import ais.tee.data.model.AiProvider
import ais.tee.data.model.ProviderInputBudgetPreflight

internal const val TOKEN_ARENA_PROMPT_ONLY_CONTEXT_FINGERPRINT = "prompt-only:v1"

/**
 * Immutable Arena request snapshot created before one provider count starts.
 *
 * [prompt] is the exact text sent for counting. [requestTag] must be unique for this count
 * operation (for example a UUID generated by the platform caller) and is echoed through the
 * provider preflight result so concurrent counts cannot be cross-wired.
 */
class TokenArenaProviderPreflightRequest private constructor(
    val variantId: String,
    val prompt: String,
    val requestTag: String,
) {
    val requestContextFingerprint: String
        get() = TOKEN_ARENA_PROMPT_ONLY_CONTEXT_FINGERPRINT
    val promptFingerprint: String
        get() = stablePromptFingerprint(prompt)

    override fun toString(): String =
        "TokenArenaProviderPreflightRequest(variantId=$variantId, prompt=<redacted>, requestTag=<redacted>)"

    companion object {
        internal fun create(
            variantId: String,
            prompt: String,
            requestTag: String,
        ): TokenArenaProviderPreflightRequest {
            require(requestTag.isNotBlank()) { "Token Arena preflight request tag must not be blank" }
            return TokenArenaProviderPreflightRequest(
                variantId = variantId,
                prompt = prompt,
                requestTag = requestTag,
            )
        }
    }
}

class TokenArenaProviderPreflightResult private constructor(
    val request: TokenArenaProviderPreflightRequest,
    val budget: ProviderInputBudgetPreflight,
) {
    companion object {
        internal fun create(
            request: TokenArenaProviderPreflightRequest,
            budget: ProviderInputBudgetPreflight,
        ): TokenArenaProviderPreflightResult =
            TokenArenaProviderPreflightResult(request, budget)
    }

    override fun toString(): String =
        "TokenArenaProviderPreflightResult(request=$request, budget=<redacted>)"
}

fun TokenArenaVariant.providerPreflightRequest(
    requestTag: String,
): TokenArenaProviderPreflightRequest =
    TokenArenaProviderPreflightRequest.create(
        variantId = id,
        prompt = prompt,
        requestTag = requestTag,
    )

fun TokenArenaProviderPreflightRequest.withBudget(
    budget: ProviderInputBudgetPreflight,
): TokenArenaProviderPreflightResult {
    require(budget.requestTag == requestTag) {
        "Provider preflight result does not match the Token Arena request"
    }
    require(budget.requestContextFingerprint == requestContextFingerprint) {
        "Provider preflight result was counted with a different request context"
    }
    return TokenArenaProviderPreflightResult.create(this, budget)
}

/**
 * Records an explicit provider input-budget preflight as one Token Arena measurement.
 *
 * The provider result must echo the unique tag for the count operation. If the current Arena
 * variant changed while that request was in flight, the result is rejected rather than relabeled.
 * This conversion never sends data by itself.
 */
fun TokenArenaProviderPreflightResult.measureForArena(
    currentVariant: TokenArenaVariant,
): TokenArenaTokenMeasurement {
    require(request.variantId == currentVariant.id) {
        "Provider preflight result belongs to a different Token Arena variant"
    }
    require(request.promptFingerprint == currentVariant.promptFingerprint) {
        "Token Arena variant changed after the provider preflight started"
    }

    val preflight = budget
    require(preflight.inputTokens >= 0) { "Provider input token count must not be negative" }
    require(preflight.inputTokenLimit > 0) { "Provider input token limit must be positive" }

    val (mode, backendLabel) = when (preflight.provider) {
        AiProvider.GEMINI ->
            TokenMeasurementMode.PROVIDER_EXACT to "Gemini countTokens"
        AiProvider.CLAUDE ->
            TokenMeasurementMode.PROVIDER_ESTIMATE to "Claude messages/count_tokens"
        else ->
            throw IllegalArgumentException(
                "Token Arena provider preflight is not supported for ${preflight.provider.id}"
            )
    }

    return TokenArenaTokenMeasurement(
        variantId = request.variantId,
        promptFingerprint = request.promptFingerprint,
        tokens = preflight.inputTokens.toLong(),
        mode = mode,
        backendLabel = backendLabel,
        providerId = preflight.provider.id,
        modelName = preflight.model,
        requestContextFingerprint = preflight.requestContextFingerprint,
        inputTokenLimit = preflight.inputTokenLimit.toLong(),
    )
}
